# @Author: Nicolas Fazio <webmaster-fazio>
# @Date:   21-04-2017
# @Email:  contact@nicolasfazio.ch
# @Last modified by:   webmaster-fazio
# @Last modified time: 21-04-2017

#
# Configuration
#
language: node_js
node_js:
  - 7
sudo: required

notifications:
  email: true

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

#
# Build Lifecycle:
#

before_install:
  - nvm install node
  - nvm use node
  - npm install -g cordova ionic
  - npm install -g karma
  - ionic state clear

install: npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - karma start ./test-config/karma.conf.js --single-run  # unit tests
  - protractor test-config/protractor.conf.js      # run e2e tests against ionic
